version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.4.5
  ruby_and_mysql:
     docker:
      - image: circleci/ruby:2.4.5
        environment:
          RAILS_ENV: test
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: app_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

commands:
  wait_for_db:
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
  db_setup:
    steps:
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace

jobs:
  build:
    executor: ruby
    steps:
      - checkout
      - ruby/install-deps
  test:
    parallelism: 3
    executor: ruby_and_mysql
    steps:
      - checkout
      - ruby/install-deps
      - wait_for_db
      - db_setup
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build