version: 2.1 # CircleCI 2.1を使用

orbs: # Rubyのパッケージを使用
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.5
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Which bundler?
          command: bundle -v